<?php

return [
    'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),
    ],

    'public_provider_rates' => [
        'cache_ttl_seconds' => env('PUBLIC_PROVIDER_RATES_CACHE_TTL_SECONDS', 15),
        'market_cache_ttl_seconds' => env('PUBLIC_PROVIDER_MARKET_RATE_CACHE_TTL_SECONDS', 3600),
        'market_base_url' => env('PUBLIC_PROVIDER_MARKET_RATE_BASE_URL', 'https://open.er-api.com/v6/latest'),
    ],

    'identity_verification' => [
        'provider' => env('IDENTITY_VERIFICATION_PROVIDER', 'origin_capture'),
        'session_ttl_minutes' => env('IDENTITY_VERIFICATION_SESSION_TTL_MINUTES', 60),
        'evidence_disk' => env('IDENTITY_VERIFICATION_EVIDENCE_DISK', 'kyc_private'),
    ],

    'business_registry' => [
        'timeout' => env('BUSINESS_REGISTRY_TIMEOUT', 12),
        'eu_vies' => [
            'endpoint' => env('EU_VIES_ENDPOINT', 'https://ec.europa.eu/taxation_customs/vies/services/checkVatService'),
            'countries' => [
                'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL',
                'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK',
                'SI', 'ES', 'SE',
            ],
        ],
        'au' => [
            'guid' => env('ABN_LOOKUP_GUID'),
            'json_url' => env('ABN_LOOKUP_JSON_URL', 'https://abr.business.gov.au/json'),
        ],
        'sg' => [
            'datastore_url' => env('DATA_GOV_SG_DATASTORE_URL', 'https://data.gov.sg/api/action/datastore_search'),
            'dataset_ids' => array_filter([
                'A' => env('ACRA_DATASET_A_ID'),
                'B' => env('ACRA_DATASET_B_ID'),
                'C' => env('ACRA_DATASET_C_ID'),
                'D' => env('ACRA_DATASET_D_ID'),
                'E' => env('ACRA_DATASET_E_ID'),
                'F' => env('ACRA_DATASET_F_ID'),
                'G' => env('ACRA_DATASET_G_ID'),
                'H' => env('ACRA_DATASET_H_ID'),
                'I' => env('ACRA_DATASET_I_ID'),
                'J' => env('ACRA_DATASET_J_ID'),
                'K' => env('ACRA_DATASET_K_ID'),
                'L' => env('ACRA_DATASET_L_ID'),
                'M' => env('ACRA_DATASET_M_ID'),
                'N' => env('ACRA_DATASET_N_ID'),
                'O' => env('ACRA_DATASET_O_ID'),
                'P' => env('ACRA_DATASET_P_ID'),
                'Q' => env('ACRA_DATASET_Q_ID'),
                'R' => env('ACRA_DATASET_R_ID'),
                'S' => env('ACRA_DATASET_S_ID'),
                'T' => env('ACRA_DATASET_T_ID'),
                'U' => env('ACRA_DATASET_U_ID'),
                'V' => env('ACRA_DATASET_V_ID'),
                'W' => env('ACRA_DATASET_W_ID'),
                'X' => env('ACRA_DATASET_X_ID'),
                'Y' => env('ACRA_DATASET_Y_ID'),
                'Z' => env('ACRA_DATASET_Z_ID'),
                'others' => env('ACRA_DATASET_OTHERS_ID'),
            ]),
        ],
    ],

    'currenxie' => [
        'base_url' => env('CURRENXIE_BASE_URL'),
        'api_key' => env('CURRENXIE_API_KEY'),
        'api_secret' => env('CURRENXIE_API_SECRET'),
        'timeout' => env('CURRENXIE_TIMEOUT', 30),
        'auth' => [
            'mode' => env('CURRENXIE_AUTH_MODE', 'static_headers'),
            'token' => env('CURRENXIE_BEARER_TOKEN'),
            'token_url' => env('CURRENXIE_TOKEN_URL'),
            'token_endpoint' => env('CURRENXIE_TOKEN_ENDPOINT', '/oauth2/token'),
            'client_id' => env('CURRENXIE_CLIENT_ID'),
            'client_secret' => env('CURRENXIE_CLIENT_SECRET'),
            'scope' => env('CURRENXIE_SCOPE'),
            'audience' => env('CURRENXIE_AUDIENCE'),
            'credentials_in' => env('CURRENXIE_AUTH_CREDENTIALS_IN', 'body'),
            'cache_key' => env('CURRENXIE_TOKEN_CACHE_KEY', 'provider_http_client:currenxie:access_token'),
            'cache_buffer_seconds' => env('CURRENXIE_TOKEN_CACHE_BUFFER_SECONDS', 30),
        ],
        'customer_endpoint' => env('CURRENXIE_CUSTOMER_ENDPOINT', '/customers'),
        'account_endpoint' => env('CURRENXIE_ACCOUNT_ENDPOINT', '/accounts'),
        'accounts_sync_endpoint' => env('CURRENXIE_ACCOUNTS_SYNC_ENDPOINT', '/accounts'),
        'balances_sync_endpoint' => env('CURRENXIE_BALANCES_SYNC_ENDPOINT', '/balances'),
        'transactions_sync_endpoint' => env('CURRENXIE_TRANSACTIONS_SYNC_ENDPOINT', '/transactions'),
        'quote_endpoint' => env('CURRENXIE_QUOTE_ENDPOINT', '/quotes'),
        'transfer_endpoint' => env('CURRENXIE_TRANSFER_ENDPOINT', '/transfers'),
        'beneficiary_endpoint' => env('CURRENXIE_BENEFICIARY_ENDPOINT', '/beneficiaries'),
        'beneficiary_update_endpoint' => env('CURRENXIE_BENEFICIARY_UPDATE_ENDPOINT', '/beneficiaries/{beneficiary}'),
        'beneficiary_delete_endpoint' => env('CURRENXIE_BENEFICIARY_DELETE_ENDPOINT', '/beneficiaries/{beneficiary}'),
        'webhook_secret' => env('CURRENXIE_WEBHOOK_SECRET'),
        'webhook_signature_header' => env('CURRENXIE_WEBHOOK_SIGNATURE_HEADER', 'X-Currenxie-Signature'),
        'webhook_signature_algorithm' => env('CURRENXIE_WEBHOOK_SIGNATURE_ALGORITHM', 'sha256'),
    ],

    'wise' => [
        'base_url' => env('WISE_BASE_URL'),
        'timeout' => env('WISE_TIMEOUT', 30),
        'auth' => [
            'mode' => env('WISE_AUTH_MODE', 'client_credentials'),
            'token' => env('WISE_BEARER_TOKEN'),
            'token_url' => env('WISE_TOKEN_URL'),
            'token_endpoint' => env('WISE_TOKEN_ENDPOINT', '/oauth/token'),
            'client_id' => env('WISE_CLIENT_ID'),
            'client_secret' => env('WISE_CLIENT_SECRET'),
            'scope' => env('WISE_SCOPE'),
            'audience' => env('WISE_AUDIENCE'),
            'credentials_in' => env('WISE_AUTH_CREDENTIALS_IN', 'basic'),
            'cache_key' => env('WISE_TOKEN_CACHE_KEY', 'provider_http_client:wise:access_token'),
            'cache_buffer_seconds' => env('WISE_TOKEN_CACHE_BUFFER_SECONDS', 30),
        ],
        'profiles_endpoint' => env('WISE_PROFILES_ENDPOINT', '/v2/profiles'),
        'public_profile_id' => env('WISE_PUBLIC_PROFILE_ID'),
        'balances_endpoint' => env('WISE_BALANCES_ENDPOINT', '/v4/profiles/{profile}/balances'),
        'account_details_endpoint' => env('WISE_ACCOUNT_DETAILS_ENDPOINT', '/v1/profiles/{profile}/account-details'),
        'transactions_endpoint' => env('WISE_TRANSACTIONS_ENDPOINT', '/v1/profiles/{profile}/balance-statements/{balance}/statement.json'),
        'quote_endpoint' => env('WISE_QUOTE_ENDPOINT', '/v3/profiles/{profile}/quotes'),
        'transfer_endpoint' => env('WISE_TRANSFER_ENDPOINT', '/v1/transfers'),
        'transfer_retrieve_endpoint' => env('WISE_TRANSFER_RETRIEVE_ENDPOINT', '/v1/transfers/{transfer}'),
        'transfer_fund_endpoint' => env('WISE_TRANSFER_FUND_ENDPOINT', '/v3/profiles/{profile}/transfers/{transfer}/payments'),
        'recipient_endpoint' => env('WISE_RECIPIENT_ENDPOINT', '/v1/accounts'),
        'webhook_secret' => env('WISE_WEBHOOK_SECRET'),
        'webhook_signature_header' => env('WISE_WEBHOOK_SIGNATURE_HEADER', 'X-Signature-SHA256'),
        'webhook_public_key' => env('WISE_WEBHOOK_PUBLIC_KEY'),
    ],

    'airwallex' => [
        'base_url' => env('AIRWALLEX_BASE_URL'),
        'timeout' => env('AIRWALLEX_TIMEOUT', 30),
        'api_version' => env('AIRWALLEX_API_VERSION'),
        'auth' => [
            'mode' => env('AIRWALLEX_AUTH_MODE', 'airwallex_access_token'),
            'token' => env('AIRWALLEX_BEARER_TOKEN'),
            'token_url' => env('AIRWALLEX_TOKEN_URL'),
            'token_endpoint' => env('AIRWALLEX_TOKEN_ENDPOINT', '/api/v1/authentication/login'),
            'client_id' => env('AIRWALLEX_CLIENT_ID'),
            'client_secret' => env('AIRWALLEX_CLIENT_SECRET'),
            'scope' => env('AIRWALLEX_SCOPE'),
            'audience' => env('AIRWALLEX_AUDIENCE'),
            'credentials_in' => env('AIRWALLEX_AUTH_CREDENTIALS_IN', 'body'),
            'cache_key' => env('AIRWALLEX_TOKEN_CACHE_KEY', 'provider_http_client:airwallex:access_token'),
            'cache_buffer_seconds' => env('AIRWALLEX_TOKEN_CACHE_BUFFER_SECONDS', 30),
        ],
        'x_api_key' => env('AIRWALLEX_API_KEY'),
        'global_accounts_endpoint' => env('AIRWALLEX_GLOBAL_ACCOUNTS_ENDPOINT', '/api/v1/global_accounts'),
        'balances_endpoint' => env('AIRWALLEX_BALANCES_ENDPOINT', '/api/v1/balances/current'),
        'transactions_endpoint' => env('AIRWALLEX_TRANSACTIONS_ENDPOINT', '/api/v1/pa/payment_events/search'),
        'quote_endpoint' => env('AIRWALLEX_QUOTE_ENDPOINT', '/api/v1/quotes/create'),
        'quote_validity' => env('AIRWALLEX_QUOTE_VALIDITY', 'MIN_15'),
        'transfer_endpoint' => env('AIRWALLEX_TRANSFER_ENDPOINT', '/api/v1/transfers/create'),
        'transfer_retrieve_endpoint' => env('AIRWALLEX_TRANSFER_RETRIEVE_ENDPOINT', '/api/v1/transfers/{transfer}'),
        'beneficiary_endpoint' => env('AIRWALLEX_BENEFICIARY_ENDPOINT', '/api/v1/beneficiaries/create'),
        'beneficiary_update_endpoint' => env('AIRWALLEX_BENEFICIARY_UPDATE_ENDPOINT', '/api/v1/beneficiaries/{beneficiary}'),
        'beneficiary_delete_endpoint' => env('AIRWALLEX_BENEFICIARY_DELETE_ENDPOINT', '/api/v1/beneficiaries/{beneficiary}'),
        'webhook_secret' => env('AIRWALLEX_WEBHOOK_SECRET'),
        'webhook_signature_header' => env('AIRWALLEX_WEBHOOK_SIGNATURE_HEADER', 'x-signature'),
        'webhook_timestamp_header' => env('AIRWALLEX_WEBHOOK_TIMESTAMP_HEADER', 'x-timestamp'),
        'webhook_signature_algorithm' => env('AIRWALLEX_WEBHOOK_SIGNATURE_ALGORITHM', 'sha256'),
    ],

    'pingpong' => [
        'base_url' => env('PINGPONG_BASE_URL', 'https://test-gateway.pingpongx.com'),
        'timeout' => env('PINGPONG_TIMEOUT', 30),
        'auth' => [
            'mode' => env('PINGPONG_AUTH_MODE', 'pingpong_access_token'),
            'token_endpoint' => env('PINGPONG_TOKEN_ENDPOINT', '/v2/token/get'),
            'app_id' => env('PINGPONG_APP_ID'),
            'app_secret' => env('PINGPONG_APP_SECRET'),
            'cache_key' => env('PINGPONG_TOKEN_CACHE_KEY', 'provider_http_client:pingpong:access_token'),
            'cache_buffer_seconds' => env('PINGPONG_TOKEN_CACHE_BUFFER_SECONDS', 300),
        ],
        'recipient_create_endpoint' => env('PINGPONG_RECIPIENT_CREATE_ENDPOINT', '/api/recipient/v2/create'),
        'recipient_update_endpoint' => env('PINGPONG_RECIPIENT_UPDATE_ENDPOINT', '/api/recipient/v2/update'),
        'recipient_delete_endpoint' => env('PINGPONG_RECIPIENT_DELETE_ENDPOINT', '/api/recipient/v2/delete'),
        'payment_create_endpoint' => env('PINGPONG_PAYMENT_CREATE_ENDPOINT', '/api/payout/v2/create'),
        'payment_query_endpoint' => env('PINGPONG_PAYMENT_QUERY_ENDPOINT', '/api/payout/v2/query'),
    ],

    'tazapay' => [
        'base_url' => env('TAZAPAY_BASE_URL'),
        'timeout' => env('TAZAPAY_TIMEOUT', 30),
        'public_key' => env('TAZAPAY_PUBLIC_KEY'),
        'account_id' => env('TAZAPAY_ACCOUNT_ID'),
        'tz_account_id' => env('TAZAPAY_TZ_ACCOUNT_ID'),
        'auth' => [
            'mode' => env('TAZAPAY_AUTH_MODE', 'basic_auth'),
            'username' => env('TAZAPAY_API_KEY'),
            'password' => env('TAZAPAY_API_SECRET'),
        ],
        'beneficiary_endpoint' => env('TAZAPAY_BENEFICIARY_ENDPOINT', '/v3/beneficiary'),
        'beneficiary_update_endpoint' => env('TAZAPAY_BENEFICIARY_UPDATE_ENDPOINT', '/v3/beneficiary/{beneficiary}'),
        'quote_endpoint' => env('TAZAPAY_QUOTE_ENDPOINT', '/v3/payout/quote'),
        'payout_endpoint' => env('TAZAPAY_PAYOUT_ENDPOINT', '/v3/payout'),
        'payout_retrieve_endpoint' => env('TAZAPAY_PAYOUT_RETRIEVE_ENDPOINT', '/v3/payout/{transfer}'),
        'balance_endpoint' => env('TAZAPAY_BALANCE_ENDPOINT', '/v3/balance'),
        'webhook_secret' => env('TAZAPAY_WEBHOOK_SECRET'),
        'webhook_signature_header' => env('TAZAPAY_WEBHOOK_SIGNATURE_HEADER'),
    ],

    'unlimit' => [
        'base_url' => env('UNLIMIT_BASE_URL', 'https://sandbox.cardpay.com/api'),
        'timeout' => env('UNLIMIT_TIMEOUT', 30),
        'auth' => [
            'mode' => env('UNLIMIT_AUTH_MODE', 'unlimit_access_token'),
            'token_url' => env('UNLIMIT_TOKEN_URL'),
            'token_endpoint' => env('UNLIMIT_TOKEN_ENDPOINT', '/auth/token'),
            'terminal_code' => env('UNLIMIT_TERMINAL_CODE'),
            'password' => env('UNLIMIT_TERMINAL_PASSWORD'),
            'grant_type' => env('UNLIMIT_GRANT_TYPE', 'password'),
            'cache_key' => env('UNLIMIT_TOKEN_CACHE_KEY', 'provider_http_client:unlimit:access_token'),
            'cache_buffer_seconds' => env('UNLIMIT_TOKEN_CACHE_BUFFER_SECONDS', 30),
        ],
        'payment_methods_endpoint' => env('UNLIMIT_PAYMENT_METHODS_ENDPOINT', '/payment_methods'),
        'payment_endpoint' => env('UNLIMIT_PAYMENT_ENDPOINT', '/payments'),
        'payment_retrieve_endpoint' => env('UNLIMIT_PAYMENT_RETRIEVE_ENDPOINT', '/payments/{payment}'),
        'payout_endpoint' => env('UNLIMIT_PAYOUT_ENDPOINT', '/payouts'),
        'payout_retrieve_endpoint' => env('UNLIMIT_PAYOUT_RETRIEVE_ENDPOINT', '/payouts/{payout}'),
        'payout_update_endpoint' => env('UNLIMIT_PAYOUT_UPDATE_ENDPOINT', '/payouts/{payout}'),
        'refund_endpoint' => env('UNLIMIT_REFUND_ENDPOINT', '/refunds'),
        'refund_retrieve_endpoint' => env('UNLIMIT_REFUND_RETRIEVE_ENDPOINT', '/refunds/{refund}'),
        'webhook_secret' => env('UNLIMIT_WEBHOOK_SECRET'),
        'webhook_signature_header' => env('UNLIMIT_WEBHOOK_SIGNATURE_HEADER', 'Signature'),
    ],

    'nium' => [
        'base_url' => env('NIUM_BASE_URL'),
        'timeout' => env('NIUM_TIMEOUT', 30),
        'client_id' => env('NIUM_CLIENT_ID'),
        'auth' => [
            'mode' => env('NIUM_AUTH_MODE', 'header'),
            'header_name' => env('NIUM_AUTH_HEADER_NAME', 'x-api-key'),
            'header_value' => env('NIUM_API_KEY'),
        ],
        'health_endpoint' => env('NIUM_HEALTH_ENDPOINT', '/api/v1/client/{client}'),
        'customer_endpoint' => env('NIUM_CUSTOMER_ENDPOINT'),
        'wallet_balance_endpoint' => env('NIUM_WALLET_BALANCE_ENDPOINT', '/api/v1/client/{client}/customer/{customer}/wallet/{wallet}/balance'),
        'wallet_transactions_endpoint' => env('NIUM_WALLET_TRANSACTIONS_ENDPOINT', '/api/v1/client/{client}/customer/{customer}/wallet/{wallet}/transactions'),
        'transaction_sync_days' => env('NIUM_TRANSACTION_SYNC_DAYS', 30),
        'quote_endpoint' => env('NIUM_QUOTE_ENDPOINT', '/api/v1/client/{client}/quotes'),
        'beneficiary_endpoint' => env('NIUM_BENEFICIARY_ENDPOINT', '/api/v2/client/{client}/customer/{customer}/beneficiaries'),
        'beneficiary_update_endpoint' => env('NIUM_BENEFICIARY_UPDATE_ENDPOINT'),
        'beneficiary_delete_endpoint' => env('NIUM_BENEFICIARY_DELETE_ENDPOINT'),
        'account_verification_endpoint' => env('NIUM_ACCOUNT_VERIFICATION_ENDPOINT', '/api/v1/client/{client}/customer/{customer}/accountVerification'),
        'transfer_endpoint' => env('NIUM_TRANSFER_ENDPOINT', '/api/v1/client/{client}/customer/{customer}/wallet/{wallet}/remittance'),
        'transfer_status_endpoint' => env('NIUM_TRANSFER_STATUS_ENDPOINT', '/api/v1/client/{client}/customer/{customer}/wallet/{wallet}/remittance/{transfer}/audit'),
        'webhook_secret' => env('NIUM_WEBHOOK_SECRET'),
        'webhook_signature_header' => env('NIUM_WEBHOOK_SIGNATURE_HEADER'),
        'webhook_signature_algorithm' => env('NIUM_WEBHOOK_SIGNATURE_ALGORITHM', 'sha256'),
    ],

    'managed_exchange_rates' => [
        'refresh_interval_seconds' => env('MANAGED_EXCHANGE_RATE_REFRESH_INTERVAL_SECONDS', 300),
    ],

    'bank_rate_sources' => [
        'enabled' => env('BANK_RATE_SYNC_ENABLED', true),
        'timeout' => env('BANK_RATE_SYNC_TIMEOUT', 20),
        'audiences' => array_values(array_filter(array_map(
            'trim',
            explode(',', env('BANK_RATE_SYNC_AUDIENCES', 'public,authenticated'))
        ))),
        'sources' => [
            'vcb' => [
                'enabled' => env('BANK_RATE_VCB_ENABLED', true),
                'code' => 'vcb',
                'name' => 'Vietcombank',
                'url' => env('BANK_RATE_VCB_URL', 'https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx'),
                'accept' => 'application/xml,text/xml,*/*',
                'parser' => 'vietcombank_xml',
                'display_order' => 10,
            ],
            'techcombank' => [
                'enabled' => env('BANK_RATE_TECHCOMBANK_ENABLED', true),
                'code' => 'techcombank',
                'name' => 'Techcombank',
                'url' => env('BANK_RATE_TECHCOMBANK_URL', 'https://techcombank.com/content/techcombank/web/vn/en/cong-cu-tien-ich/ty-gia/_jcr_content.exchange-rates.integration.json'),
                'accept' => 'application/json,*/*',
                'parser' => 'techcombank_json',
                'display_order' => 40,
            ],
        ],
    ],
];
