<?php

return [
    'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),
    ],

    'currenxie' => [
        'base_url' => env('CURRENXIE_BASE_URL'),
        'api_key' => env('CURRENXIE_API_KEY'),
        'api_secret' => env('CURRENXIE_API_SECRET'),
        'timeout' => env('CURRENXIE_TIMEOUT', 30),
        'auth' => [
            'mode' => env('CURRENXIE_AUTH_MODE', 'static_headers'),
            'token' => env('CURRENXIE_BEARER_TOKEN'),
            'token_url' => env('CURRENXIE_TOKEN_URL'),
            'token_endpoint' => env('CURRENXIE_TOKEN_ENDPOINT', '/oauth2/token'),
            'client_id' => env('CURRENXIE_CLIENT_ID'),
            'client_secret' => env('CURRENXIE_CLIENT_SECRET'),
            'scope' => env('CURRENXIE_SCOPE'),
            'audience' => env('CURRENXIE_AUDIENCE'),
            'credentials_in' => env('CURRENXIE_AUTH_CREDENTIALS_IN', 'body'),
            'cache_key' => env('CURRENXIE_TOKEN_CACHE_KEY', 'provider_http_client:currenxie:access_token'),
            'cache_buffer_seconds' => env('CURRENXIE_TOKEN_CACHE_BUFFER_SECONDS', 30),
        ],
        'customer_endpoint' => env('CURRENXIE_CUSTOMER_ENDPOINT', '/customers'),
        'account_endpoint' => env('CURRENXIE_ACCOUNT_ENDPOINT', '/accounts'),
        'accounts_sync_endpoint' => env('CURRENXIE_ACCOUNTS_SYNC_ENDPOINT', '/accounts'),
        'balances_sync_endpoint' => env('CURRENXIE_BALANCES_SYNC_ENDPOINT', '/balances'),
        'transactions_sync_endpoint' => env('CURRENXIE_TRANSACTIONS_SYNC_ENDPOINT', '/transactions'),
        'quote_endpoint' => env('CURRENXIE_QUOTE_ENDPOINT', '/quotes'),
        'transfer_endpoint' => env('CURRENXIE_TRANSFER_ENDPOINT', '/transfers'),
        'beneficiary_endpoint' => env('CURRENXIE_BENEFICIARY_ENDPOINT', '/beneficiaries'),
        'beneficiary_update_endpoint' => env('CURRENXIE_BENEFICIARY_UPDATE_ENDPOINT', '/beneficiaries/{beneficiary}'),
        'beneficiary_delete_endpoint' => env('CURRENXIE_BENEFICIARY_DELETE_ENDPOINT', '/beneficiaries/{beneficiary}'),
        'webhook_secret' => env('CURRENXIE_WEBHOOK_SECRET'),
        'webhook_signature_header' => env('CURRENXIE_WEBHOOK_SIGNATURE_HEADER', 'X-Currenxie-Signature'),
        'webhook_signature_algorithm' => env('CURRENXIE_WEBHOOK_SIGNATURE_ALGORITHM', 'sha256'),
    ],

    'wise' => [
        'base_url' => env('WISE_BASE_URL'),
        'timeout' => env('WISE_TIMEOUT', 30),
        'auth' => [
            'mode' => env('WISE_AUTH_MODE', 'client_credentials'),
            'token' => env('WISE_BEARER_TOKEN'),
            'token_url' => env('WISE_TOKEN_URL'),
            'token_endpoint' => env('WISE_TOKEN_ENDPOINT'),
            'client_id' => env('WISE_CLIENT_ID'),
            'client_secret' => env('WISE_CLIENT_SECRET'),
            'scope' => env('WISE_SCOPE'),
            'audience' => env('WISE_AUDIENCE'),
            'credentials_in' => env('WISE_AUTH_CREDENTIALS_IN', 'body'),
            'cache_key' => env('WISE_TOKEN_CACHE_KEY', 'provider_http_client:wise:access_token'),
            'cache_buffer_seconds' => env('WISE_TOKEN_CACHE_BUFFER_SECONDS', 30),
        ],
        'profiles_endpoint' => env('WISE_PROFILES_ENDPOINT', '/v1/profiles'),
        'balances_endpoint' => env('WISE_BALANCES_ENDPOINT', '/v4/profiles/{profile}/balances'),
        'transactions_endpoint' => env('WISE_TRANSACTIONS_ENDPOINT', '/v1/borderless-accounts/{profile}/statement.json'),
        'quote_endpoint' => env('WISE_QUOTE_ENDPOINT', '/v3/profiles/{profile}/quotes'),
        'transfer_endpoint' => env('WISE_TRANSFER_ENDPOINT', '/v1/transfers'),
        'recipient_endpoint' => env('WISE_RECIPIENT_ENDPOINT', '/v1/accounts'),
        'webhook_secret' => env('WISE_WEBHOOK_SECRET'),
    ],

    'airwallex' => [
        'base_url' => env('AIRWALLEX_BASE_URL'),
        'timeout' => env('AIRWALLEX_TIMEOUT', 30),
        'auth' => [
            'mode' => env('AIRWALLEX_AUTH_MODE', 'none'),
            'token' => env('AIRWALLEX_BEARER_TOKEN'),
            'token_url' => env('AIRWALLEX_TOKEN_URL'),
            'token_endpoint' => env('AIRWALLEX_TOKEN_ENDPOINT', '/api/v1/authentication/login'),
            'client_id' => env('AIRWALLEX_CLIENT_ID'),
            'client_secret' => env('AIRWALLEX_CLIENT_SECRET'),
            'scope' => env('AIRWALLEX_SCOPE'),
            'audience' => env('AIRWALLEX_AUDIENCE'),
            'credentials_in' => env('AIRWALLEX_AUTH_CREDENTIALS_IN', 'body'),
            'cache_key' => env('AIRWALLEX_TOKEN_CACHE_KEY', 'provider_http_client:airwallex:access_token'),
            'cache_buffer_seconds' => env('AIRWALLEX_TOKEN_CACHE_BUFFER_SECONDS', 30),
        ],
        'x_api_key' => env('AIRWALLEX_API_KEY'),
        'global_accounts_endpoint' => env('AIRWALLEX_GLOBAL_ACCOUNTS_ENDPOINT', '/api/v1/global_accounts'),
        'balances_endpoint' => env('AIRWALLEX_BALANCES_ENDPOINT', '/api/v1/balances/current'),
        'transactions_endpoint' => env('AIRWALLEX_TRANSACTIONS_ENDPOINT', '/api/v1/pa/payment_events/search'),
        'quote_endpoint' => env('AIRWALLEX_QUOTE_ENDPOINT', '/api/v1/quotes/create'),
        'transfer_endpoint' => env('AIRWALLEX_TRANSFER_ENDPOINT', '/api/v1/transfers/create'),
        'beneficiary_endpoint' => env('AIRWALLEX_BENEFICIARY_ENDPOINT', '/api/v1/beneficiaries/create'),
        'webhook_secret' => env('AIRWALLEX_WEBHOOK_SECRET'),
    ],
];
